apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-alertmanager
  namespace: dev
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local
  ports:
    - port: 9093
      targetPort: 9093
