apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana
  namespace: dev
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
  ports:
    - port: 3000
      targetPort: 80

