appName: urlshortener
namespace: dev
replicaCount: 2
image:
  repository: "paragon40/url_shortener"
  tag: 19d1166e9a155c8d4a179c01d29d4f5b2b0e0b54-1777900515
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env: {}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: d882d65204ed4afd42b1d002d2189eff2847433e8ecf57ebe372615ceae7d8b1
  generatedAt: 2026-05-04T13:16:41Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /live
    initialDelaySeconds: 10
    periodSeconds: 15
