apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:pMxNmbQs,iv:IJb+FJO2HcAfa/xk09ct2quGyn9qB1CNX5hwKPJMplA=,tag:pBq6icz/VK9LcQb5OD3uxw==,type:str]
    admin-password: ENC[AES256_GCM,data:6En40puh,iv:C+2FvIYUs8cFXRNsl2tkIRM/7lS6+a0S0Yx7VGlqDfs=,tag:XkcJ9ndjkaSBAEL3dXIkgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOEVhOUlIeFViMkJjbW81
            Q3kxYUh4T1lwRUo2UVlrbTFWd2lxczBoY1YwCjhwbDl5ZmplY25rVVJSUFNLTDBS
            dkFzSlEycWxpVmtzc0xZYkt5UE1RUjgKLS0tIFpMem85dUx3WjlpdTZacTFCcnhm
            Nnh0dFFna001d3MwQmMyYVhzOUVPMkUKU5F4X22XfELK+/fd6rf2wyc4+Cg1bmBG
            PBTvYADBcCr8hsaFXL8TmINt0bFtNrW8cu4IIjeOQ/PzUQ2UU4LFMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19u9pmsn4845rghpmrmfh4vnvgm7jwad2njacfq5td9nnu7jawfvqr88alg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T15:42:35Z"
    mac: ENC[AES256_GCM,data:mVzTjoFs4WHVeLT+fk3Cc3Zj388O1BjdC86a4T28zYe+6rBrGkXa3WXe0EWn66Pi6mxZeID01BEqPBznd4mh3DODEMfnMjRpArNoBLZLsETdgakTtuq2jYvZWKvBNbqaAVCsIhQOFf1cPX4sMShwZ8qxO2Cr9Fh38l07ISQqdW8=,iv:UzfwNyZmTvDgotU1/M6GFHi8obXs9ILvnf2/ZNbnCJU=,tag:ZycE0io9Qp+Buo5FDvkA1g==,type:str]
    version: 3.13.1
