apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:SFyfeIZm,iv:FOLrlC+Gek4sZCsIjkXPggyepJejRPggfHFDJnarP90=,tag:h+rIQuHPT1KqoE1GVoEspQ==,type:str]
    admin-password: ENC[AES256_GCM,data:0XDpqDPk,iv:IDi/w+07zW508HzIBcFzWWFORx+BiJDQSrOMkNfd1lo=,tag:UV9jCl24uXTyYe5o+3T3Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NU03LzdtaWFDd1kxS3Z2
            OXg2cUF6NC9ua1dxT2Zpd3Rib1NYQ3l3TFhBClBrSjJvSnJlMEU3L2ZRU2V4TCs1
            emM2bzJIRFh1ZE5jQ1R4eE5OR2s5UlEKLS0tIFNHNlo1VEpCME5tNkozMWF2Rkpn
            WmpHOFlYZGNPdWxHSXVyMkNmZ2JVYmsKekqNmr1CNN2WT8QiD64c3IYNgQLZkOnv
            DzKU6/l4x0dbqEhARylcMTQ+P8jOsMp83ARld70zlMCX8Hi8gVsw8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1scfdeeyeassgvmey569kn5xwtl47gh3v0gqkuu0ndyhaajdr2a6s6dswul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T11:57:09Z"
    mac: ENC[AES256_GCM,data:J6KYvkzztqFlZ/hRO1SnGaiO/OkMjxUnsawAQCBVmTAmgOzC5E9/BfCYDkVpM975XKq9ob0AWP77P0J85kj8LoOG7awik9j38Hw8mJwp9yyrK4CRSYcSL0LReX+Uh2geUTyB2qbYZTZQcZxCu2Q/w75qlUj82rnKcc+tdI8Kj/Q=,iv:WZiYF7oBKDNC5yGAPP4anxNzFfUOXbPj71pBIuhZ4Uw=,tag:hDy2DQUooivRaSIHmzRyXA==,type:str]
    version: 3.13.1
