apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:lhvBQEVB,iv:i8Pc92UPDua9t0KoQgmigEmLMPTUWKGWVlFeXNj51HM=,tag:NZr8GJoWOi2kck2gj4JylA==,type:str]
    admin-password: ENC[AES256_GCM,data:A4WX/BKB,iv:oBLtj550NwIl6XzEsGlFbEKvbiCO76iAENANRDTm19E=,tag:zVQ9HUI8gG9RwJbciyiVLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaWJtZDdmOXY2cnJvYU5V
            MWhxRnMrazluMThsZW5GaXRmUDBoa21lM1g4CjRXK05JM1U3UEFPTCtqN2dFeWJP
            UFl0SDk1OG05NHd1TENJMzZmRkVONWcKLS0tIEFEVlRNRFhxQmNqY3I3MFZnb2VM
            SVhhWkFlamh6UWFxT2hDWVpJS0xjeFUK2bQcDuOvAoVW679Z8jEd9kqTXclsmFgL
            sqPdxvsPdaA5Gc84VsLBiQ3RHTXPjNzzqeO9oz84grePNeKQVNU+mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19u9pmsn4845rghpmrmfh4vnvgm7jwad2njacfq5td9nnu7jawfvqr88alg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T14:48:10Z"
    mac: ENC[AES256_GCM,data:Oyjzge1Cu4LusSCFtR5w5E+TC8YWwmYXlVL8+kUdo1eSorIOgof3yyu8/nT+JebEXv6bJAymXyzkuS8GmRNdzNpAoeI/cjjaA1jqE9rCW/JxeDM8VCN73ETu412VPZyR8qev17xOi8WXqXHsh0yYJW04kmhLB/v6TTsLXBeIWpQ=,iv:BZdHSJA1aZjEQao4VgB1O0IPc/ot3QdbIy5qhsOrd0A=,tag:iKvmhYn3wWv6VfiagwQq3Q==,type:str]
    version: 3.13.1
