apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: hashicorp/http-echo
          args:
            - "-text=Admin Service"
          ports:
            - containerPort: 80
