creation_rules:

  # GitOps Kubernetes secrets
  - path_regex: gitops/secrets/.*\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age: age1cecg8a84aghxneyezx0knaw0tfyrv939z76wh8j9y9ew69adlc8sjexx6a

  # Terraform tfvars files
  - path_regex: iac/.*\.tfvars$
    age: age1cecg8a84aghxneyezx0knaw0tfyrv939z76wh8j9y9ew69adlc8sjexx6a

  # Docker app secrets
  - path_regex: docker/.*/.*secret.*\.ya?ml$
    age: age1cecg8a84aghxneyezx0knaw0tfyrv939z76wh8j9y9ew69adlc8sjexx6a
