
service:
  name: admin
  compute: ec2

app:
  port: 4000
  appUser: admin_app
  healthPath: /health
  livePath: /live
  basePath: /

deploy:
  env: dev
  containerUid: 10003

storage:
  volumes:
    - name: admin
      emptyDir: {}

  volumeMounts:
    - name: admin
      mountPath: /data

features:
  topVolume:
    enabled: true
  tmp:
    enabled: true
