
service:
  name: admin

app:
  port: 4000
  appUser: admin_app
  healthPath: /health
  livePath: /live
  basePath: /

deploy:
  env: dev
  containerUid: 10003

storage:
  volumes:
    - name: admin_volume
      emptyDir: {}

  volumeMounts:
    - name: admin_mnt
      mountPath: /data

features:
  topVolume:
    enabled: true
  tmp:
    enabled: true
