
service:
  name: chatbot

app:
  port: 5000
  appUser: chatbot_app
  healthPath: /health
  livePath: /live
  basePath: /

deploy:
  env: dev
  containerUid: 10007

storage:
  volumes:
    - name: chatbot-vol
      emptyDir: {}

  volumeMounts:
    - name: chatbot-vol
      mountPath: /data

features:
  topVolume:
    enabled: true
  tmp:
    enabled: true
  serviceMonitor:
    enabled: true
