defaults:
  repo: https://github.com/paragon40/kubapp.git
  chart_path: gitops/charts/apps

services:
  admin:
    values:
      dev: gitops/envs/dev/admin/values.yaml
      prod: gitops/envs/prod/admin/values.yaml

  user:
    values:
      dev: gitops/envs/dev/user/values.yaml
      prod: gitops/envs/prod/user/values.yaml

