appName: node-db-order-app
namespace: dev
serviceAccount:
  create: true
  name: node-db-order-app-sa
  roleArn: arn:aws:iam::259183055744:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: false
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/node_db_order_app
  tag: 2fa6b7ba58-2026-10-08-13-29-54
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 15
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  cpu: 70
  memory: 70
meta:
  staticFingerprint: 4d376c60cf63a391da2eae4e540b1bd78c536dc5d7ffeaca3d4b84415761399b
  generatedAt: 2026-10-08T13:32:59Z
  source: build-pipeline
db:
  enabled: true
  secretName: node-db-order-app-db-secrets
nodeSelector:
  compute: ec2
tolerations:
  - key: compute
    operator: Equal
    value: ec2
    effect: NoSchedule
