server {
    listen 80;
    server_name sys-monitor.rundailytest.site;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name sys-monitor.rundailytest.site;

    ssl_certificate /etc/letsencrypt/live/sys-monitor.rundailytest.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sys-monitor.rundailytest.site/privkey.pem;

    # ---------------------------
    # GitHub Webhook
    # ---------------------------
    location /webhook/github {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # ---------------------------
    # Grafana
    # ---------------------------
    location /grafana/ {
        proxy_pass http://127.0.0.1:3001$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # ---------------------------
    # Prometheus
    # ---------------------------
    location /prometheus/ {
        proxy_pass http://127.0.0.1:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
