appName: url_shortener
namespace: dev
replicaCount: 2
image:
  repository: codest40/url_shortener:baab37a1703558fceeb138a0db51a79ba6f7adc0
  tag: baab37a1703558fceeb138a0db51a79ba6f7adc0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env: {}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: f5ed585cbc7e602b2cfd099b560d3fedd14ed74753dc41730c10c36af9065ce6
  generatedAt: 2026-04-29T13:11:27Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
