appName: chatbot
namespace: dev
replicaCount: 2
image:
  repository: paragon40/chat_bot
  tag: f989682fd030e7d6f9676ad77dc9c0e4c417d8eb-1778080413
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10007
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /live
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 15
  startup:
    httpGet:
      path: /health
      port: 5000
    failureThreshold: 30
    periodSeconds: 5
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
  memory: 70
meta:
  staticFingerprint: def604b97c2b41f7538b782a321adfea6b59beeaa3d9e1510c30e813586f6823
  generatedAt: 2026-05-06T15:15:16Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
storage:
  volumes:
    - name: chatbot-vol
      emptyDir: {}
  volumeMounts:
    - name: chat-mnt
      mountPath: /data
