apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubapp-ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}

    alb.ingress.kubernetes.io/scheme: {{ .Values.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.targetType }}

    alb.ingress.kubernetes.io/listen-ports: '{{ toJson .Values.listenPorts }}'

    alb.ingress.kubernetes.io/ssl-redirect: "{{ .Values.sslRedirect }}"

    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.acmArn }}

    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host }}

spec:
  ingressClassName: {{ .Values.ingressClass }}

  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.services.user.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.user.name }}
                port:
                  number: {{ .Values.services.user.port }}

          - path: {{ .Values.services.admin.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.admin.name }}
                port:
                  number: {{ .Values.services.admin.port }}
