apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: codest40/edgeapp:Bv-1774266373-92dfe6-R142-green
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: postgresql://kubuser:kubpassword@postgres:5432/kubapp

            - name: USE_SQLITE
              value: "false"

            - name: BOTH_DB
              value: "false"

            - name: RUN_MIGRATIONS
              value: "true"

      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 500m
