apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: codest40/edgeapp:Bv-1774266373-92dfe6-R142-green
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "postgresql://test:test@dummy:5432/testdb"
          ports:
            - containerPort: 8080
