appName: nodejsapp
namespace: dev
replicaCount: 2
image:
  repository: "paragon40/nodejs_app"
  tag: bc3abe5ec891cdc1b2008b170c5e47592a932f3d-1777972318
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env: {}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: 741778c54be115a02f8b4b9e662483e03f36b2c42b6ef7faac2395a58adad34f
  generatedAt: 2026-05-05T09:13:34Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10004
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    path: /api/health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /api/live
    initialDelaySeconds: 10
    periodSeconds: 15
