appName: nodejsapp
namespace: dev
serviceAccount:
  create: true
  name: nodejsapp-sa
  roleArn: arn:aws:iam::198200019771:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: false
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/nodejs_app
  tag: 499d3609c7f2fde19b07cbcc072991aa063d08be-1778331817
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10004
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /api/live
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 15
  startup:
    httpGet:
      path: /api/health
      port: 3000
    failureThreshold: 30
    periodSeconds: 5
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
  memory: 70
meta:
  staticFingerprint: 741778c54be115a02f8b4b9e662483e03f36b2c42b6ef7faac2395a58adad34f
  generatedAt: 2026-05-09T13:05:13Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
