appName: app

namespace: dev

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m

env: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpu: 70

securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

