host: dev.kubapp.yourdomain.com
acmArn: DEV_CERT_ARN

ingressClass: alb
scheme: internet-facing
targetType: ip
sslRedirect: "443"

listenPorts:
  - HTTP: 80
  - HTTPS: 443

services:
  - name: user-service
    path: /user
    port: 80

  - name: admin-service
    path: /admin
    port: 80
