apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/timzapone/kubapp-project.git
    targetRevision: main
    path: gitops/apps/admin/chart
    helm:
      valueFiles:
        - ../../../envs/dev/apps/admin/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: admin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
