
service:
  name: nodejsapp

app:
  port: 3000
  appUser: nodejs_app
  healthPath: /api/health
  livePath: /api/live
  basePath: /

deploy:
  env: dev
  containerUid: 10004

runtime:
  env:
    NODE_ENV: developement
    REDIS_HOST: redis-service
    REDIS_PORT: "6379"
    LOG_LEVEL: info

storage:
  volumes:
    - name: nodejs-volume
      emptyDir: {}

  volumeMounts:
    - name: nodejs-mnt
      mountPath: /data

features:
  topVolume:
    enabled: false
  tmp:
    enabled: false

