
service:
  name: metrics

app:
  port: 8080
  appUser: metric_app
  healthPath: /health
  livePath: /live
  basePath: /

deploy:
  env: dev
  containerUid: 10009


storage:
  volumes:
    - name: vol-metrics
      emptyDir: {}

  volumeMounts:
    - name: mount-metrics
      mountPath: /data

features:
  topVolume:
    enabled: true
  tmp:
    enabled: true
  serviceMonitor:
    enabled: true
