replicas: 2

image:
  repository: codest40/java_dir
  tag: 1773749177
  pullPolicy: IfNotPresent

service:
  name: admin-service
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

health:
  path: /transaction
  initialDelaySeconds: 10
  periodSeconds: 10

env: []
