appName: user

namespace: dev

replicaCount: 2

image:
  repository: codest40/edgeapp
  tag: latest-green
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m

env:
  DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
  USE_SQLITE: "true"
  BOTH_DB: "false"
  RUN_MIGRATIONS: "true"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu: 70

