appName: admin
namespace: dev
replicaCount: 2
image:
  repository: "paragon40/admin_app"
  tag: 19d1166e9a155c8d4a179c01d29d4f5b2b0e0b54-1777900511
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 4000
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env: {}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: be9cdf8b48982e22e4b67e6b6345e115a9ffde654c29143eaf57dff2b5007ecb
  generatedAt: 2026-05-04T13:16:40Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /live
    initialDelaySeconds: 10
    periodSeconds: 15
