replicas: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  path: /user

service:
  port: 80

strategy:
  maxUnavailable: 0
  maxSurge: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

health:
  path: /user
  initialDelaySeconds: 10
  periodSeconds: 10

env: []
