appName: notification
namespace: dev
replicaCount: 2
image:
  repository: codest40/nodejs_app:b3c0b355c5535ac78401afe5cd5bda998079e89d
  tag: b3c0b355c5535ac78401afe5cd5bda998079e89d
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env:
  NODE_ENV: developement
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  LOG_LEVEL: info
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: 7ec8d0b9fad67e88c8837e9fa95517e5330fef0838a6ed3c71340888383e6fc2
  generatedAt: 2026-05-01T10:05:56Z
  source: build-pipeline
  runtimeHash: c028fb8cf52adbd06e5a9ad09a541d5a1b920c144d1dfb7195457d975cfd54ab
