
service:
  name: weather

app:
  port: 80
  appUser: weather_app
  healthPath: /health
  livePath: /live
  basePath: /

deploy:
  env: dev
  containerUid: 10006

runtime:
  env:
    DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
    USE_SQLITE: "true"
    BOTH_DB: "true"
    RUN_MIGRATIONS: "true"

storage:
  volumes:
    - name: edgepaas-vol
      emptyDir: {}

  volumeMounts:
    - name: edgepaas-mnt
      mountPath: /tmp

features:
  topVolume:
    enabled: true
  tmp:
    enabled: true

