
service:
  name: weather

app:
  port: 80
  healthPath: /health

deploy:
  env: dev
  user: weather_app
  containerUid: 10006

runtime:
  env:
    DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
    USE_SQLITE: "true"
    BOTH_DB: "false"
    RUN_MIGRATIONS: "true"


