
service:
  name: weather

app:
  port: 80
  healthPath: /health

deploy:
  env: dev
  user: weather_app
  containerUid: 10006

volumeMounts:
  - name: tmp
    mountPath: /tmp

volumes:
  - name: tmp
    emptyDir: {}

runtime:
  env:
    DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
    USE_SQLITE: "true"
    BOTH_DB: "true"
    RUN_MIGRATIONS: "true"


