secrets:
    OPENWEATHER_API_KEY: ENC[AES256_GCM,data:rL8Sy0kgyP0Q/4F/BQdHKC8Sc2YMlM2+Brtsfe6sMjo=,iv:itKa7kaE+IRxLt5It+6KT+j1da7F25hqm9IsEUaJBr8=,tag:UVWk8xLSe4b+2GowrD8joA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:/HYKVreoeYujQV2LoOTRt+MDYQeGhSAT,iv:lAu6A6IX2O0DWh4EyKHTpPlUpqfN4IY673n1KuT0JQg=,tag:l502LUIW91p9ZWnAYnd/3A==,type:str]
    EMAIL_TO: ENC[AES256_GCM,data:uTjJXy1d1pAL/Pxvtj+f02P7seUwug==,iv:sdLYQVNdwJg5nNFGO8wIm6J6lEFaLGEcOsTb6KSHOuA=,tag:gGD/lP3EKePfvpV31ZseOg==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:9eneQumR3CrXmi+bsMyi7A==,iv:6fQevWK4Q5X8J3YfDnjeBm2i1Pomab4onutaBm/JPNQ=,tag:NbPehbcmOuvoP/Ijur3ahw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scfdeeyeassgvmey569kn5xwtl47gh3v0gqkuu0ndyhaajdr2a6s6dswul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bi8xTFZLbjhsWlVUaUdP
            dHkzQzRhajU1eFd5enlDMHlvNEl4dTRzNFM0CnV1d1RMWlUrVkQrTHRmUzdVYU5L
            KzYrcjl3QmZWOWlqUVhoQ2N5cGFDVEUKLS0tIEpsUndZdlVIMkFiZFlLQTU5SHlW
            cjN0TEZjUlZLQUtITlExTHNVeDdGRUkK+FIFT5XazvmwLrDkqv5cKRgnnJ1ja0O+
            DNkHNNt/xwwVUOzMoOLgRo7vn3hbwHPX34n0M8PyrHJVvPvsOoEm/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:27:06Z"
    mac: ENC[AES256_GCM,data:9O2rt0jyZ5mpOvUwumqDo8ffz8VW33xngEceUZ14X27zv9+glYpc8Qcyo6dXl7QTp1W9JgR5raIIBdtlhv4t49YKu6zZneJfLchoq9krfBC9Kr/HlKjK7cdZXkX1j0ZjaicIv4eAH1JBlzumcbViDejnKx6IvyU7S3HS+OUFStQ=,iv:ERsEqaGopVsInGbXGAWk/cJL3fOf1dLLCe+zlSWbBfk=,tag:be12rm0oJtVzkcrKOAYMJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
