secrets:
    OPENWEATHER_API_KEY: ENC[AES256_GCM,data:jXnMW+Fo8ZjV/GlpIUB/bJ7r5zKrWphyaTQqqrCCQbw=,iv:bG+MujiXWgdJm8/vStE4NDA2Zea1Q4mzgv1bQpSBfHM=,tag:ZAh2aVG/QEDlp7q9EOYd3Q==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:q43tHGXjVtkwsvNyXGBvYdYM1Z+E6Q==,iv:nZPn203lS2RjlfnZOKcP4dZJUp9rsGJKpt2TJECndYU=,tag:sGb02eM+WwAlGyBcZcvGng==,type:str]
    EMAIL_TO: ENC[AES256_GCM,data:fyEBM1FO4wg6ykcaF/I/MFpO08dZ4ekn,iv:so3fW0x9wxjwjHUj6kW/XBDOEwXLtj5a27QlGtYGEa4=,tag:MQal4Mq709fQZElz75od1w==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:xOd3JgcTom2KBcBKFkePww==,iv:wpGjs0CDP0hYSLUyO0kzbhOruP6ekY/J4M8IZmzIvME=,tag:8cEROQm/45pzFr6ZfAftjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab2k2aE5pTHMyM2hXZzB0
            bStjRFVRL0s5dzNyanBlZWh1RU1zYmNvdnprCmViUTBWMjA5QS9JR1MxOVFLc1Qy
            VWl4dEpic2RBWmJQUWZ2V3pqSFFFWWcKLS0tIHNWMVFOcXVBbm9pL2lRNTRRYXdq
            cTJBQ0p0dDlyVUVNY2lqbk1ycy9WQnMKlBrmuQeVHdiGtRAiJqq38LcdG+oxsF3q
            dWqFZ8d7nJMNS4Xf6ArFLYf9ColfbhfAxO4dIxphGStoHvK+aPpaXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19u9pmsn4845rghpmrmfh4vnvgm7jwad2njacfq5td9nnu7jawfvqr88alg
    lastmodified: "2026-06-08T12:52:45Z"
    mac: ENC[AES256_GCM,data:vZBmPzrLHMnu62jzlLNpI0JCY+jwQuCERKkuM07EDIJ4IKf314uuikXSkvZdOxhzdcchHR2m6JdOA0+x1QNiAL6gbEI3JT0N6RNsNdhfEDQGE/6PsqdiZZnwGttPj5imU4mA8PwzElbkZIwScbRXCqlhuT85adl4bcOjgDV83VE=,iv:I0NXdpNYfmbyTVo0Z33hCkqWhNBR7qb5rKRXpU4uFwg=,tag:zyqtzF2STEd5sMaRjCsCfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
