secrets:
    OPENWEATHER_API_KEY: ENC[AES256_GCM,data:Fk4Dnl8m1bHE04WAXo3LqTJLyqKde8eCPRoxOIDfwXI=,iv:ZnT8/5aZwPzYmfItd7gbgw0SALMiPilUqwTzQ00ZEmI=,tag:7Q1SkXbKxqQfYhMnCpmgbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scfdeeyeassgvmey569kn5xwtl47gh3v0gqkuu0ndyhaajdr2a6s6dswul
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bE5nRW9sbHVKdUc2UlBI
            T0N4K0J6QVB5YTRzSzBVdDVvS2djRmtwd25jCkg5MlFPZjF5dHh3UU5Zemo3M0ZC
            b2FML3p6S0VWOXJlZFRabVREUnZHbVEKLS0tIE5HY21LZkJ5RTB3YkRka0lMUWhF
            cGUzWldBbm9rVlg2eng5dXBCWGxNemMKxO/ikB7N+xEXjxv5izGdBwZtR8chXDB1
            JMqDW1dj3OMq5jde5DS1RKrpih+3FEzp6rB0wbecbD3ePf1nWjnVgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T14:18:00Z"
    mac: ENC[AES256_GCM,data:421BRVtnyxjY1HeuaFXhP5Rnu+1m0VDCbwtD1YZ3yU+Lmu+pPjABIa6RgjAAQkV1pU6iaJoO/gYjHZvMW8Oh9ciSWj/0NEGz+uWbVMGQ+iHUUpxn+SKfahcl6aTH29ySbfW2ws91yuL7sY6GvEDltshdnASBGIbWVVrFOehrEJ0=,iv:UToSe5O+/T/WrhRWQgr1kvcJ4Jfl+7ugtzxjIv0wT0Q=,tag:mPTuSD8EAjKkwT4T5AZNJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
