apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubapp
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/paragon40/kubapp.git
        revision: main
        directories:
          - path: envs/*/*

  template:
    metadata:
      name: "{{path[2]}}-{{path[1]}}"
      labels:
        env: "{{path[1]}}"
        app: "{{path[2]}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main

        path: gitops/charts/apps

        helm:
          valueFiles:
            - "../../{{path}}/values.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
