apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubapp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/paragon40/kubapp.git
        revision: main
        directories:
          - path: gitops/apps/*

  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

