apiVersion: v1
kind: Secret
metadata:
  name: github-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/paragon40/kubapp.git
  githubAppID: "3440391"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAp/B314VNTe1Gqu8rwO9Owuq/gDS3NK4ufU3s3BLS11DKFod3
    WeVrziBu8k5fl8ixKqNlMrv4hHcyWyC4P9QsiL8UaVL811JXkTEqlBlySAgsJ6SN
    7UpZnMkH25v8hfa6PYxp7XZhgpqWn9GZp+sWl0c86W13vOzDrevTldOMCxIA5S2l
    JV0wTy3z3ZBE/XzgXniD8EsmcgLZ0l416kc6/lJNptd7yNAmW6wANIbnGoZptTJG
    3xM6pzXSwq4IXOpuhhMca0iIKtUnJK2grZdUQ86zYXow0WtZjSpfPgNfj+mRaIJb
    PnSNdZLqysnjBURpkLpdOcgriJbQuvbz/t6O8QIDAQABAoIBAC9+XAYBVtlg7wlM
    Vk1b4CRTixDQ17b4Q4GAVinu0N2/pUc1zFUKArDqjzXLYFFmmmP6jZYJfsDHjOAk
    ora6ZFXP5A/dPlAOo2EWTHpRr/YbCZG0gcbHrgwe9i/vLz0bh5P8b8COKAlteod8
    GT5Zx6vEo79IDALL2pMHDHFkwEgou+4mGXOBiyqp/4E9r/750x9JSh+LKI3hclUJ
    fOwwTlzwStrWrQvjO4RHhrqPZpT5DI1/8/9k9AVXYHHur1//BdSyAaJCIZ0SPZOc
    jSYNQnLMyuwhhmBenbeRA7CeAVLw15Z8mlzna8t8xXIJ7tny22q7m9PTJDQi9Ha6
    c8nfyDkCgYEA1fgShD67G0R7znBJhFRJJTrgGwpt1PMB1Pv2CpUmejLlMMHAGrzl
    zgK2pPHij3JiHW/YJXCH4P/C4wjT4CsQpXGYARQ0GJMoYIhKagfkEp7aILNiOUJj
    rvkDXnqGKsT0vj5mbFbz+IPTivA3rENAk+dC6RxBYfTD6AfUbG3qf6sCgYEAyO2v
    iPgpROmyFq+INN6oo2TW9fBtWm6maAEXAgKYaqSaq1AzFqUXdv2Bba9YHAl/PuST
    Nekvj4vVFzYmDVyNp1OF7mQKBekdefs/7QvS6FwedMbzKeSK/nIGhr/f2wbDEKqz
    TlPZooXyhdq+1+xXIemR4gPZfvj4Yz+KJLhE/9MCgYEAzKGsa8dmwEQ1t5AR7zmA
    ntd4vsOxmKgzR1MU0rgkDVghcwjJRYkEqopTzNn8WD4HcammaN//Q4K3CtRFda0a
    BW/m9Jky3ZHXWsLdkBwt1lUPvZhxRtukZBGIVFIPgFXOzyb0Y4ahWzoQFV95jwje
    eNUCW9iG+zzQI1dho7VXQHMCgYBjpBtMnWQ53HqIbXvqXBDdFoDTbeuM0RqMsR2r
    zYWwPPjGw/rR3AUK6SRqNG5JWRxVIB0wuvbvBLUj0aKFNcS5md3tHocp7zTC7SoC
    b76jpCsmVhL4T3HuRLWf1T856tyJQ12wFjzzL+HZJ2VExtte4emKX8ZYBTeIYFYt
    Z4QwKQKBgBH4yoceo1hzzu+cRBW6YD6fDRrqIR3fLUObKBSsP6tqnr0kZoTohjN2
    q00aJQgRJAWZ1/1qZaOyCgzOnr9Tco/1knxHxG9R1v3RoyqSY0KxCv+eEo0N1gmZ
    Q1aPn2WSf2yoieTKLmZAwNFpfM/+WwN5feLsZI1tuEWys7mcY6o4
    -----END RSA PRIVATE KEY-----
