apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - env: dev
          #- env: prod

  template:
    metadata:
      name: "ingress-{{env}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main

        path: gitops/charts/ingress

        helm:
          valueFiles:
            #- "envs/{{env}}/ingress/values.yaml"
            - "../../envs/{{env}}/ingress/values.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

