apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:

          - list:
              elements:
                - env: dev
                  namespace: dev
                # - env: prod
                #   namespace: prod

          - list:
              elements:
                - stack: values
                - stack: monitoring

  template:
    metadata:
      name: "ingress-{{.env}}-{{.stack}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main

        path: gitops/charts/ingress

        helm:
          valueFiles:
            #- "ingress/{{env}}/values.yaml"
            - "../../ingress/{{.env}}/{{.stack}}.yaml"


      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ if eq .stack \"monitoring\" }}monitoring{{ else }}{{ .namespace }}{{ end }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

