appName: weather
namespace: dev
replicaCount: 2
image:
  repository: "paragon40/weather_app"
  tag: 19d1166e9a155c8d4a179c01d29d4f5b2b0e0b54-1777900510
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env:
  DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
  USE_SQLITE: "true"
  BOTH_DB: "true"
  RUN_MIGRATIONS: "true"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: 033053f9f27634740e5344868cde3d60024926bbe12bba243690b82a33dec19c
  generatedAt: 2026-05-04T13:16:41Z
  source: build-pipeline
  runtimeHash: 5ed34709aeed0ff460b53f186304146fe8473dd9e1f8551a935e9339779d5906
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /live
    initialDelaySeconds: 10
    periodSeconds: 15
