appName: weather
namespace: dev
replicaCount: 2
image:
  repository: paragon40/weather_app:27e3fa0fe87bc4dbf8e8e0bc8f8a3c5cbca1f699-1777656371
  tag: 27e3fa0fe87bc4dbf8e8e0bc8f8a3c5cbca1f699
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
env:
  DATABASE_URL: postgresql://kubuser:kubpassword@postgres:5432/kubapp
  USE_SQLITE: "true"
  BOTH_DB: "false"
  RUN_MIGRATIONS: "true"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
meta:
  staticFingerprint: 033053f9f27634740e5344868cde3d60024926bbe12bba243690b82a33dec19c
  generatedAt: 2026-05-01T17:27:24Z
  source: build-pipeline
  runtimeHash: d16529b49fe81f077d385c99f4d726f39b37ac62c4e66d7c79ee770e19d24e7f
