appName: weather
namespace: dev
replicaCount: 2
image:
  repository: "paragon40/weather_app"
  tag: ca36bfc10509d3785c3db75ae2e2f0dafab3c71f-1778225495
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 70
  memory: 70
meta:
  staticFingerprint: 033053f9f27634740e5344868cde3d60024926bbe12bba243690b82a33dec19c
  generatedAt: 2026-05-08T07:43:52Z
  source: build-pipeline
  runtimeHash: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsUser: 10006
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    path: /health
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    httpGet:
      path: /health
      port: 80
  liveness:
    path: /live
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
    httpGet:
      path: /live
      port: 80
  startup:
    httpGet:
      path: /health
      port: 80
    failureThreshold: 30
    periodSeconds: 5
storage:
  volumes:
    - name: edgepaas-vol
      emptyDir: {}
  volumeMounts:
    - name: edgepaas-mnt
      mountPath: /tmp
serviceAccount:
  create: true
  name: weather-sa
  roleArn: arn:aws:iam::198200019771:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
