host: kubapp.rundailytest.site

ingressClass: alb

scheme: internet-facing
targetType: ip

sslRedirect: "443"

listenPorts:
  - HTTP: 80
  - HTTPS: 443

acmArn: arn:aws:acm:us-east-1:198200019771:certificate/a98757d4-69b3-4a6b-a01e-407622169dcc
