name: GitOps Test

on:
  push: {}
  workflow_dispatch:

jobs:
  Test-Development-env:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Trigger gitops
        run: |
          ./scripts/apply_argocd.sh

