name: Build and Push Docker Images

on:
  push: {}
  pull_request:
    paths:
      - "docker/**"

  workflow_dispatch:
    inputs:
      mode:
        description: Build mode
        required: false
        default: cached
        type: choice
        options:
          - cached
          - fresh

      env:
        description: Env mode
        required: false
        default: dev
        type: choice
        options:
          - dev
          - prod

      service:
        description: "Optional single service build (empty = all)"
        required: false
        default: ""

####################################################
# PREPARE MATRIX
####################################################
jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Generate dynamic matrix
        id: set-matrix
        run: |
          MANUAL_SERVICE="${{ github.event.inputs.service }}"

          if [ -n "$MANUAL_SERVICE" ]; then
            echo "Manual build mode: $MANUAL_SERVICE"
            SERVICES=$(echo "[\"$MANUAL_SERVICE\"]" | jq -c '.')
          else
            SERVICES=$(find docker -mindepth 1 -maxdepth 1 -type d -not -path "*/\.*" -printf '%f\n' \
              | sort \
              | jq -R -s -c 'split("\n") | map(select(length > 0))')
          fi

          echo "matrix={\"service\":$SERVICES}" >> $GITHUB_OUTPUT

          if [ "$SERVICES" = "[]" ]; then
            echo "No services found in docker/"
            exit 1
          fi

####################################################
# BUILD JOB
####################################################
  build:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    env:
      REGISTRY: docker.io
      IMAGE_NAMESPACE: ${{ secrets.DOCKER_USER }}

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: paragon40/kubapp
          token: ${{ steps.app-token.outputs.token }}

      ####################################################
      # LOGIN
      ####################################################
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login $REGISTRY \
            -u "${{ secrets.DOCKER_USER }}" --password-stdin

      ####################################################
      # LOAD SOURCE OF TRUTH
      ####################################################
      - name: Load service metadata to github Reg
        run: |
          SERVICE="${{ matrix.service }}"
          CONTEXT="docker/$SERVICE"

          APP_FILE=$(find "$CONTEXT" -maxdepth 1 -type f \
            \( -name "kubapp.yaml" -o -name "kubapp.yml" \) \
            -print -quit)

          SECRET_FILE=$(find "$CONTEXT" -maxdepth 1 -type f \
            \( -name "secrets.yaml" -o -name "secrets.yml" -o -name "secret.yaml" -o -name "secret.yml" \) \
            -print -quit)

          SERVICE_NAME="$SERVICE"
          PORT="80"
          ENV="${{ github.event.inputs.env || 'dev' }}"
          NO_VARS=true

          # override from app file if exists
          if [[ -n "$APP_FILE" && -s "$APP_FILE" ]]; then
            echo "Using app file: $APP_FILE"
            SERVICE_NAME=$(yq e '.service.name // env(SERVICE)' "$APP_FILE")
            PORT=$(yq e '.app.port // 80' "$APP_FILE")
            ENV=$(yq e '.deploy.env // strenv(ENV)' "$APP_FILE")

            VAR_COUNT=$(yq e '.runtime.env // {} | length' "$APP_FILE")
            if [[ "$VAR_COUNT" -gt 0 ]]; then
              NO_VARS=false
            fi
          else
            echo "No app file found → using defaults"
          fi
          echo "NO_VARS=$NO_VARS" >> $GITHUB_ENV

          if [[ -n "$SECRET_FILE" && -s "$SECRET_FILE" ]]; then
            echo "Secrets file detected: $SECRET_FILE"
            echo "NO_SECRETS=false" >> $GITHUB_ENV
          else
            echo "NO_SECRETS=true" >> $GITHUB_ENV
          fi

          NAMESPACE="$ENV"
          IMAGE="$IMAGE_NAMESPACE/$SERVICE:$GITHUB_SHA"

          mkdir -p gitops/registry/$ENV

          cat > gitops/registry/$ENV/$SERVICE.json <<EOF
          {
            "service": "$SERVICE_NAME",
            "context": "$CONTEXT",
            "image": "$IMAGE",
            "tag": "$GITHUB_SHA",
            "registry": "$REGISTRY",
            "namespace": "$NAMESPACE",
            "env": "$ENV",
            "port": "$PORT",
            "NO_VARS": "$NO_VARS",
            "NO_SECRETS": "$NO_SECRETS"
          }
          EOF

          echo "Generated manifest for $SERVICE"

          if [ -f "$SECRET_FILE" ]; then
            echo "Secrets file detected"
          fi

      ####################################################
      # BUILD
      ####################################################
      - name: Build Docker image
        run: |
          MODE="${{ github.event.inputs.mode }}"
          MODE=${MODE:-cached}

          IMAGE="$IMAGE_NAMESPACE/${{ matrix.service }}:${{ github.sha }}"
          IMAGE2="$IMAGE_NAMESPACE/${{ matrix.service }}:latest"
          CONTEXT="docker/${{ matrix.service }}"

          if [ "$MODE" = "fresh" ]; then
            echo "Fresh build (no cache)"
            docker build --no-cache -t "$IMAGE" "$CONTEXT"
            docker build --no-cache -t "$IMAGE2" "$CONTEXT"
          else
            echo "Cached build"
            docker build -t "$IMAGE" "$CONTEXT"
            docker build -t "$IMAGE2" "$CONTEXT"
          fi

      ####################################################
      # PUSH
      ####################################################
      - name: Push image
        run: |
          IMAGE="$IMAGE_NAMESPACE/${{ matrix.service }}:${{ github.sha }}"
          IMAGE2="$IMAGE_NAMESPACE/${{ matrix.service }}:latest"
          docker push "$IMAGE"
          docker push "$IMAGE2"

      ####################################################
      # Github Registry
      ####################################################
      - name: Commit Metadata
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          set -euo pipefail
          SERVICE="${{ matrix.service }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add gitops/registry/
          if git diff --cached --quiet; then
            echo "No chages detected"  && exit 0
          fi

          git commit -m "[BUILD_APP] Registry update: $SERVICE"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/paragon40/kubapp.git
          git push
