name: Remove App

on:
  workflow_dispatch:
    inputs:
      service:
        required: true
      env:
        required: true

permisisons:
  contents: write

jobs:
  remove:
    uses: ./.github/workflows/runner.yml
    with:
      script: scripts/remove_app.sh
      args: "${{ inputs.service }} ${{ inputs.env }}"
