name: Argocd And Gitops Bootstrap

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # --------------------------------
      # 1. Checkout repo
      # --------------------------------
      - name: Checkout repo
        uses: actions/checkout@v4


      # --------------------------------
      # 2. AWS credentials
      # --------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check AWS credentials
        run: aws sts get-caller-identity

      # --------------------------------
      # 3. Setup kubeconfig (EKS access)
      # --------------------------------
      - name: Setup kubeconfig
        run: |
          set -e

          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name kubapp-dev

          export KUBECONFIG=~/.kube/config

          echo "✅ kubeconfig created"

          kubectl cluster-info

      - name: Check
        run: |
          set -e
          echo "=== kubeconfig ==="
          cat ~/.kube/config || true
          echo "=== auth test ==="
          kubectl auth can-i get pods -A || true

      - name: Check Readiness
        run: bash scripts/check_cluster.sh

      # --------------------------------
      # 4. Apply ArgoCD GitHub App repo secret
      # --------------------------------
      - name: Apply ArgoCD GitHub App secret
        run: |
          set -e

          SECRET_FILE=$(find gitops/secrets -type f -name "github-repo-secret.*" | head -n 1)

          if [ -n "$SECRET_FILE" ]; then
            echo "Decrypting secret file: $SECRET_FILE"
            sops -d "$SECRET_FILE" | kubectl apply --validate=false -f -
            echo "✅ ArgoCD secret applied from Sops"
          else
            echo "❌ No encrypted secret files found. Generating one"
            python3 scripts/apply_argo_secret.py
            kubectl apply --validate=false -f gitops/secrets/github-repo-secret.yaml
            echo "✅ ArgoCD secret applied from Script"
          fi
        env:
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      # --------------------------------
      # 5. Verify ArgoCD resources
      # --------------------------------
      - name: Verify ArgoCD namespace access
        run: kubectl get ns argocd

      - name: Verify secret exists
        run: kubectl get secret -n argocd | grep github || true

      # --------------------------------
      # 5. Apply ArgoCD resources
      # --------------------------------
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Make script executable
        run: chmod +x scripts/bootstrap_gitops.sh

      - name: Run GitOps bootstrap
        run: bash scripts/bootstrap_gitops.sh
