name: Argocd Setup

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create ArgoCD GitHub App secret
        run: |
          kubectl create secret generic github-app-repo \
            -n argocd \
            --from-literal=url=https://github.com/paragon40/kubapp.git \
            --from-literal=githubAppID=3440391 \
            --from-file=githubAppPrivateKey=<(printf "%s" "$APP_PRIVATE_KEY") \
            --dry-run=client -o yaml | kubectl apply -f -
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Apply ArgoCD secret
        run: kubectl apply -f gitops/argocd/github-repo-secret.yaml

      - name: Make setup script executable
        run: chmod +x scripts/setup_argocd.sh

      - name: Setup ArgoCD -> GitHub integration
        run: bash scripts/setup_argocd.sh
        env:
          APP_ID: ${{ secrets.APP_ID_GITHUB }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}
          INSTALLATION_ID: ${{ secrets.CLIENT_ID }}
          REPO_URL: ${{ secrets.REPO_URL }}
          ENV: ${{ secrets.env }}
