name: Terraform Provision

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to run
        required: true
        type: choice
        options:
          - apply
          - destroy
      env:
        description: Environment
        required: false
        default: dev
        type: choice
        options:
          - dev

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Infra Init and Validate
        working-directory: iac/infra
        run: |
          terraform init
          terraform validate

      - name: K8s Init and Validate
        working-directory: iac/k8s
        run: |
          terraform init
          terraform validate

      - name: Apply Infra and K8s
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          echo "APPLY MODE"

          echo "Infra apply"
          cd iac/infra
          terraform apply -auto-approve -var-file="terraform.tfvars"

          echo "K8s apply"
          cd ../k8s
          terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Destroy K8s and Infra
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          echo "DESTROY MODE"

          echo "Destroy K8s first"
          cd iac/k8s
          terraform destroy -auto-approve -var-file="terraform.tfvars"

          echo "Destroy Infra second"
          cd ../infra
          terraform destroy -auto-approve -var-file="terraform.tfvars"

