name: Test Terrafom

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to run
        required: true
        type: choice
        options: [apply, destroy]

      env:
        description: Environment
        required: true
        default: dev
        type: choice
        options: [dev, prod]

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.event.inputs.env }}
  cancel-in-progress: false

jobs:
  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    name: Destroy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install SOPS
        run: |
          curl -L -o sops https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup AGE key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt

      - name: Set ENV
        run: echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV

      - name: Destroy K8s
        working-directory: iac/k8s
        run: |
          set -euo pipefail
          terraform init -reconfigure -backend-config="envs/${ENV}/backend.hcl"
          terraform validate
          sops -d envs/${ENV}/k8s.tfvars.enc > k8s.tfvars
          terraform destroy -auto-approve -var-file=k8s.tfvars

      - name: Destroy Infra
        working-directory: iac/infra
        run: |
          set -euo pipefail
          terraform init -reconfigure -backend-config="envs/${ENV}/backend.hcl"
          terraform validate
          sops -d envs/${ENV}/infra.tfvars.enc > infra.tfvars
          terraform destroy -auto-approve -var-file=infra.tfvars
