name: SOPS Encrypt + Decrypt Test

on:
  workflow_dispatch:
  push:
    paths:
      - "gitops/secrets/**"

jobs:
  test-sops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------
      # Install tools
      # -----------------------------
      - name: Install SOPS
        run: |
          curl -L -o sops https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # -----------------------------
      # Setup AGE private key (IMPORTANT)
      # -----------------------------
      - name: Setup SOPS AGE key
        run: |
          mkdir -p ~/.config/sops/age

          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt

          chmod 600 ~/.config/sops/age/keys.txt

          echo "SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt" >> $GITHUB_ENV

      # -----------------------------
      # Decrypt test
      # -----------------------------
      - name: Debug SOPS key loading
        run: |
          sops --version
          echo "Checking key file format..."
          cat ~/.config/sops/age/keys.txt | head -c 50

      - name: Decrypt SOPS file
        run: |
          echo "🔓 Decrypting..."

          sops -d gitops/secrets/github-repo-secret.yaml.enc > decrypted.yaml

      # -----------------------------
      # Validate YAML correctness
      # -----------------------------
      - name: Validate Kubernetes manifest
        run: |
          echo "📦 Validating manifest..."
          cat decrypted.yaml

          kubectl apply --dry-run=client -f decrypted.yaml
