name: Runtime Image Update

on:
  workflow_dispatch:

concurrency:
  group: gitops-update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: paragon40/kubapp
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget -qO /usr/local/bin/yq \
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Validate GitOps structure
        run: ./scripts/validate_gitops.sh

      - name: Validate GitOps structure
        run: ./scripts/get_state_file.sh

      - name: Apply GitOps updates
        run: |
          set -e
          ENV1="${{ env.ENV }}"
          for file in $(find gitops/registry/$ENV1/*.json -name "*.json"); do
            SERVICE=$(jq -r .service "$file")
            IMAGE=$(jq -r .image "$file")
            ENV=$(jq -r .env "$file")

            if [ -z "$ENV" ] || [ "$ENV" = "null" ]; then
              echo "Invalid ENV in $file"
              exit 1
            fi

            FILE="gitops/envs/$ENV/$SERVICE/values.yaml"
            if [[ ! -f "$FILE" ]]; then
              echo "Values File for ${SERVICE}-${ENV} NOT Found"
              exit 1
            fi

            echo "Updating ${SERVICE}-${ENV}"
            echo "Target file: $FILE"

            yq e ".image.repository = strenv(IMAGE)" -i "$FILE"

          done

      - name: Commit changes
        run: |
          DATE=$(date +"%Y-%m-%d_%H-%M-%S")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git diff --quiet && {
            echo "No changes detected"
            exit 0
          }
          git commit -m "[IMAGE UPDATE: ($DATE)] Gitops Update from build pipeline" || exit 0
          if git push; then
            echo "Push Successful"
          else
            echo "Remote State Changed. Rebasing.."
            git pull --rebase
            git push
            echo "Push Successful"
          fi
