namespace: dev
ingress:
  name: kubapp-dev-alb
  className: alb
  baseDomain: rundailytest.online
  enableSubdomainRouting: true
  certificateArn: arn:aws:acm:us-east-1:198200019771:certificate/d33fdba8-5a0c-4be6-9cc7-9a7b45be19f4
  annotations:
    scheme: internet-facing
    targetType: ip
    healthcheckPath: /health
    listenPorts:
      - HTTP: 80
      - HTTPS: 443
    group: kubapp-shared
services:
  - name: weather
    enabled: true
    port: 80
  - name: metrics
    port: 80
    enabled: true
  - name: admin
    port: 80
    enabled: true
  - name: urlshortener
    port: 80
    enabled: true
  - name: grafana
    port: 3000
    enabled: true
    backend:
      service: kube-prometheus-stack-grafana
  - name: prometheus
    port: 80
    enabled: true
    backend:
      service: kube-prometheus-stack-prometheus
  - name: alertmanager
    port: 80
    enabled: true
    backend:
      service: kube-prometheus-stack-alertmanager
  - name: argocd
    port: 80
    enabled: true
    backend:
      service: argocd-server
